### DISCUSSION TITLE
How to use a Local Bot Api Server

### DISCUSSION THREAD

**Discussion by Lukasss93** [nutgram/nutgram#595] [Examples]
# How to use a Local Bot Api Server

This guide will show you how to use a local bot api server.

## Steps

1. Logout from the official bot api server

	**Vanilla:**
	```php
	$bot->deleteWebhook(); //optional
	$bot->close();
	$bot->logOut();
	// remember to set the webhook again (if you deleted it)
	```

	**Framework:**
	You can use the `nutgram:logout` command.

2. Add the following configuration keys:
	```php
	$config = new Configuration(
	    isLocal: true,
	    apiUrl: 'your-local-bot-api-server-url',
	);
	```
	See the Laravel or Symfony documentation to know how to add configuration keys.

3. Run your local bot api server

4. Enjoy!

## ⚠️ This is a real use-case example of usage with Laravel+Docker on a development environment:

1. Add the local telegram bot api server to docker-compose.yml file:

	```yml
	  telegram-bot-api:
	    container_name: telegram-bot-api
	    image: aiogram/telegram-bot-api:latest
	    environment:
	      TELEGRAM_API_ID: "11111111111111"
	      TELEGRAM_API_HASH: "xxxxxxxxxxxxxxxxxx"
	      TELEGRAM_LOCAL: "true"
	      TELEGRAM_VERBOSITY: 3
	      TELEGRAM_STAT: "true"
	    volumes:
	      - ./storage/app/telegram-bot-api/:/var/lib/telegram-bot-api/
	    ports:
	      - "8081:8081"
	      - "8082:8082"
	    networks:
	      - your-network
	```

2. <project-root>/app/Telegram/DockerPathTransformer.php
	```php
	<?php
	
	namespace App\Telegram;
	
	class DockerPathTransformer
	{
	    public function __invoke(string $path): string
	    {
	        $serverPath = sprintf("/var/lib/telegram-bot-api/%s", config('nutgram.token'));
	        $appPath = storage_path(sprintf('app/telegram-bot-api/%s', config('nutgram.token')));
	
	        return str_replace($serverPath, $appPath, $path);
	    }
	}
	```

3. php artisan nutgram:logout

4. Add the following configuration keys to your config/nutgram.php file:

	```php
	//...
	'config' => [
	    'is_local' => true,
	    'api_url' => 'telegram-bot-api:8081',
	    'local_path_transformer' => \App\Telegram\DockerPathTransformer::class,
	],
	//...
	```

5. Your handlers:

	```php
	
	$bot->onDocument(function(Nutgram $bot){
	    $document = $bot->message()->document;
	    $file = $bot->getFile($document->file_id);
	
	    $file->save(storage_path('app/doc.pdf'));
	
	    $bot->sendMessage('Document saved!');
	});
	
	```

6. Start Nutgram

7. Enjoy!

	![immagine](https://github.com/nutgram/nutgram/assets/4071613/c4ef8928-5972-4008-b68e-5b65718e2b09)
