### ISSUE TITLE
[BUG] Can't get EntityManager in Command class

### ISSUE THREAD

**Issue by sherwomeister** [nutgram/nutgram#697]
### Nutgram version

4.19.0

### PHP version

8.3

### Framework

Symfony 7

### Cache driver

apcu

### OS

Ubuntu

### Dev environment

Docker

### Describe the bug

I get this error if I try to get EM autowired: `Too few arguments to function App\Telegram\Command\SomeCommand::__construct(), 0 passed in /var/www/app/vendor/nutgram/nutgram/src/Handlers/Listeners/MessageListeners.php on line 44 and exactly 1 expected`

This also does not work:
```php
public function handle(Nutgram $bot, EntityManagerInterface $entityManager): void
{
   // ...
}
```
Nor this:
```yml
    App\Telegram\Command\SomeCommand:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
```

### To Reproduce

```php
$bot->registerCommand(SomeCommand::class)->middleware(SomeMiddleware::class);
```

```php
class SomeCommand extends Command
{

    // ...

    public function __construct(
        private readonly EntityManagerInterface $entityManager,
    )
    {
        parent::__construct();
    }
    
    // ..
}
```

### Expected behavior

How to get EM in command?
